from __future__ import annotations

import os

import requests


GITHUB_MODELS_ENDPOINT = "https://models.github.ai/inference/chat/completions"
DEFAULT_MODEL_NAME = "openai/gpt-4o-mini"
REQUEST_TIMEOUT_SECONDS = 20


def get_readable_scenario(scenario: str, custom_scenario: str) -> str:
    """Return the scenario text that should be shown to the user."""
    if scenario == "Custom scenario" and custom_scenario.strip():
        return custom_scenario.strip()

    return scenario


def format_outfit_for_prompt(outfit_name: str, outfit: dict) -> str:
    """Format one outfit as readable text for a future AI prompt."""
    lines = [f"{outfit_name}:"]

    for role, item in outfit.items():
        if item is None:
            continue

        item_text = (
            f"- {role}: {item.get('name', 'Unknown item')} "
            f"({item.get('color', 'unknown color')}, "
            f"{item.get('category', 'unknown category')}, "
            f"style tags: {', '.join(item.get('style_tags', []))})"
        )
        lines.append(item_text)

    return "\n".join(lines)


def build_explanation_prompt(
    recommendation: dict,
    scenario: str,
    custom_scenario: str,
    selected_vibes: list[str],
    comfort_preference: str,
) -> str:
    """Build a prompt that can be sent to an AI model."""
    scenario_text = get_readable_scenario(scenario, custom_scenario)
    vibes_text = ", ".join(selected_vibes) if selected_vibes else "balanced practical style"

    main_outfit_text = format_outfit_for_prompt(
        "Main outfit",
        recommendation["main_outfit"],
    )
    alternative_outfit_text = format_outfit_for_prompt(
        "Alternative outfit",
        recommendation["alternative_outfit"],
    )

    return f"""
You are Wardrobe Wizard, a friendly and practical outfit assistant.

Write a short outfit explanation for the user.

Rules:
- Be warm, useful, and concise.
- Do not mention gender identity.
- Do not suggest buying new clothes.
- Use the selected wardrobe items only.
- Explain why the main outfit works.
- Explain how the alternative outfit is different.
- Add one practical note about comfort or weather.
- Use simple English.

Scenario:
{scenario_text}

Selected style vibes:
{vibes_text}

Comfort preference:
{comfort_preference}

{main_outfit_text}

{alternative_outfit_text}

Return exactly three short sections:
1. Main outfit
2. Alternative outfit
3. Practical note
""".strip()


def create_fallback_explanation(
    recommendation: dict,
    scenario: str,
    custom_scenario: str,
    selected_vibes: list[str],
    comfort_preference: str,
) -> str:
    """Create a friendly explanation without calling an external AI model."""
    scenario_text = get_readable_scenario(scenario, custom_scenario)
    vibes_text = ", ".join(selected_vibes) if selected_vibes else "balanced practical style"

    return (
        f"For **{scenario_text}**, Wardrobe Wizard selected items that best match "
        f"the chosen vibe: **{vibes_text}**. "
        f"The main outfit is built from the highest-scoring wardrobe items for this situation, "
        f"while the alternative outfit uses different pieces where possible, so the user has a real second option. "
        f"The recommendation also considers the comfort preference: **{comfort_preference}**. "
        f"This explanation is generated by the local fallback layer, so the app remains stable even without an external AI API."
    )


def get_github_models_token() -> str | None:
    """Read the GitHub Models token from environment variables."""
    return os.getenv("GITHUB_TOKEN") or os.getenv("GH_TOKEN")


def call_github_models(prompt: str) -> str | None:
    """Call GitHub Models and return the model response text.

    If there is no token or the request fails, return None.
    The app will then use the local fallback explanation.
    """
    token = get_github_models_token()

    if not token:
        return None

    model_name = os.getenv("GITHUB_MODEL_NAME", DEFAULT_MODEL_NAME)

    headers = {
        "Accept": "application/vnd.github+json",
        "Authorization": f"Bearer {token}",
        "X-GitHub-Api-Version": "2022-11-28",
        "Content-Type": "application/json",
    }

    payload = {
        "model": model_name,
        "messages": [
            {
                "role": "system",
                "content": (
                    "You are Wardrobe Wizard, a warm and practical outfit assistant. "
                    "You explain wardrobe recommendations clearly and safely."
                ),
            },
            {
                "role": "user",
                "content": prompt,
            },
        ],
        "temperature": 0.6,
        "max_tokens": 300,
    }

    try:
        response = requests.post(
            GITHUB_MODELS_ENDPOINT,
            headers=headers,
            json=payload,
            timeout=REQUEST_TIMEOUT_SECONDS,
        )
        response.raise_for_status()
        data = response.json()

        return data["choices"][0]["message"]["content"].strip()

    except (requests.RequestException, KeyError, IndexError, TypeError, ValueError):
        return None


def generate_outfit_explanation(
    recommendation: dict,
    scenario: str,
    custom_scenario: str,
    selected_vibes: list[str],
    comfort_preference: str,
) -> str:
    """Generate an outfit explanation.

    Current behavior:
    - Try GitHub Models if a token is available.
    - If there is no token or the API call fails, use the local fallback explanation.
    """
    prompt = build_explanation_prompt(
        recommendation=recommendation,
        scenario=scenario,
        custom_scenario=custom_scenario,
        selected_vibes=selected_vibes,
        comfort_preference=comfort_preference,
    )

    ai_response = call_github_models(prompt)

    if ai_response:
        return ai_response

    return create_fallback_explanation(
        recommendation=recommendation,
        scenario=scenario,
        custom_scenario=custom_scenario,
        selected_vibes=selected_vibes,
        comfort_preference=comfort_preference,
    )


# Developer notes:
# - build_explanation_prompt() creates the text sent to the model.
# - call_github_models() sends the prompt to GitHub Models by REST API.
# - get_github_models_token() reads GITHUB_TOKEN or GH_TOKEN from the environment.
# - generate_outfit_explanation() tries real AI first and fallback second.
